name: weather_app
description: A flutter project to display the current weather information
  along with the forecast of 3 days by calling a free API .

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  google_fonts: ^3.0.1
  dcdg: ^4.0.1

  cupertino_icons: ^1.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  http: ^0.13.4

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/cities.txt
    - assets/images/sunny.jpg
    - assets/images/cloudy.png
    - assets/images/partlysunny.png
    - assets/images/rainy.png
    - assets/images/113.png
    - assets/images/116.png
    - assets/images/119.png
    - assets/images/122.png
    - assets/images/143.png
    - assets/images/176.png
    - assets/images/182.png
    - assets/images/185.png
    - assets/images/200.png
    - assets/images/227.png
    - assets/images/230.png
    - assets/images/248.png
    - assets/images/260.png
    - assets/images/263.png
    - assets/images/266.png
    - assets/images/281.png
    - assets/images/284.png
    - assets/images/293.png
    - assets/images/296.png
    - assets/images/299.png
    - assets/images/302.png
    - assets/images/305.png
    - assets/images/308.png
    - assets/images/311.png
    - assets/images/314.png
    - assets/images/317.png
    - assets/images/320.png
    - assets/images/323.png
    - assets/images/326.png
    - assets/images/329.png
    - assets/images/332.png
    - assets/images/335.png
    - assets/images/338.png
    - assets/images/350.png
    - assets/images/353.png
    - assets/images/356.png
    - assets/images/359.png
    - assets/images/362.png
    - assets/images/365.png
    - assets/images/368.png
    - assets/images/371.png
    - assets/images/374.png
    - assets/images/386.png
    - assets/images/389.png
    - assets/images/392.png
    - assets/images/395.png














  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
